apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workload-dev

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/workload/workload
    newName: image-registry.openshift-image-registry.svc:5000/workload-dev/workload
    newTag: latest

configMapGenerator:
  - name: workload-config
    behavior: replace
    literals:
      - APP_NAME=workload
      - APP_ENV=dev
      - LOG_LEVEL=debug

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  environment: dev
