apiVersion: v1
kind: ConfigMap
metadata:
  name: shipper-onboarding-api-config
  labels:
    app: shipper-onboarding-api
    app.kubernetes.io/name: shipper-onboarding-api
    app.kubernetes.io/part-of: logistics-platform
data:
  APP_NAME: shipper-onboarding-api
  APP_ENV: default
  LOG_LEVEL: info
