apiVersion: v1
kind: ConfigMap
metadata:
  name: workload-config
  labels:
    app: workload
    app.kubernetes.io/name: workload
    app.kubernetes.io/part-of: logistics-platform
data:
  APP_NAME: workload
  APP_ENV: default
  LOG_LEVEL: info
