apiVersion: v1
kind: Service
metadata:
  name: workload
  labels:
    app: workload
    app.kubernetes.io/name: workload
    app.kubernetes.io/part-of: logistics-platform
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: workload
