apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: workload-prod

bases:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: image-registry.openshift-image-registry.svc:5000/workload/workload
    newName: image-registry.openshift-image-registry.svc:5000/workload-prod/workload
    newTag: latest

configMapGenerator:
  - name: workload-config
    behavior: replace
    literals:
      - APP_NAME=workload
      - APP_ENV=prod
      - LOG_LEVEL=info

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  environment: prod
